# Generated by Django 4.2 on 2024-12-23 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='application_date',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='applied_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(default=django.utils.timezone.now, upload_to='resumes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
