# Generated by Django 4.1.13 on 2024-12-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questionresponse',
            name='unique_question_response',
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java')], max_length=50),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='level',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='topic',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='questionresponse',
            unique_together={('test_result', 'question')},
        ),
    ]
